% Create a figure handle for dynamic visualization of incoming data.
fg = figure('Units', 'normalized', 'Position', [0 0 1 1]); % Fullscreen

% Define two panels. The panel is the parent for all push buttons
panel_1 = uipanel(fg, 'Units', 'normalized', 'Position',...
    [.905 .68 .09 .12]);
ipg_1_text = uicontrol(fg, 'Style','text', 'String',...
    'IPG 1: ', 'Units', 'normalized','Position', [.905 .83 .09 .02], ...
    'FontWeight', 'bold', 'FontSize', 10);
panel_2 = uipanel(fg, 'Units', 'normalized', 'Position',...
    [.905 .22 .09 .12]);
ipg_2_text = uicontrol(fg, 'Style','text', 'String',...
    'IPG 2: ', 'Units', 'normalized','Position', [.905 .37 .09 .02], ...
    'FontWeight', 'bold', 'FontSize', 10);
panel_3 = uipanel(fg, 'Units', 'normalized', 'Position',...
    [.905 .495 .09 .12]);

% Define the push buttons. Thanks, Matt, for the tips.
start_exp_but = uicontrol(panel_3, 'Style', 'PushButton', 'String',...
    'Start w Stim Sync', 'Callback', {@start_experiment, inst_1, ...
    exp_stim_group},'Units', 'normalized', 'Position', [0 .7 1 0.45],...
    'BackgroundColor', 'black', 'ForegroundColor', 'green');
rec_only_but = uicontrol(panel_3, 'Style', 'PushButton', 'String',...
    'Start w/o Stim Sync', 'Callback', {@start_rec_only},...
    'Units', 'normalized', 'Position', [0 .335 1 .282],...
    'BackgroundColor', 'black', 'ForegroundColor', 'green');
stop_but = uicontrol(panel_3, 'Style', 'PushButton',...
    'String', 'STOP!', 'Callback', 'stop_state = 1',...
    'Units', 'normalized', 'Position', [0 .033 1 .22], ...
    'BackgroundColor', 'black', 'ForegroundColor', 'red');
stop_state = 0;


% Panel 1 UI Controls (For IPG 1)
stim_on_but_1 = uicontrol(panel_1, 'Style', 'PushButton', 'String',...
    'Stim ON', 'Callback', {@turn_stim_on, inst_1},...
    'Units', 'normalized', 'Position', [0 .8 1 .2],...
    'BackgroundColor', 'red');

stim_off_but_1 = uicontrol(panel_1, 'Style', 'PushButton', 'String',...
    'Stim OFF', 'Callback', {@turn_stim_off, inst_1},...
    'Units', 'normalized', 'Position', [0 .58 1 .2],...
    'BackgroundColor', 'green');

group_text_1 = uicontrol(panel_1, 'Style','text', 'String',...
    'Switch to: ', 'Units', 'normalized','Position', [0 .44 1 .12], ...
    'FontWeight', 'bold');

groups_popup_1 = uicontrol(panel_1, 'Style', 'popup',...
    'String', {'Group A', 'Group B', 'Group C', 'Group D'},...
    'Callback', {@switch_groups, inst_1}, 'Units', 'normalized',...
    'Position', [0 .2 1 .08]);

% Panel 2 UI Controls (For IPG 2)
stim_on_but_2 = uicontrol(panel_2, 'Style', 'PushButton', 'String',...
    'Stim ON', 'Callback', {@turn_stim_on, inst_2},...
    'Units', 'normalized', 'Position', [0 .8 1 .2],...
    'BackgroundColor', 'red');

stim_off_but_2 = uicontrol(panel_2, 'Style', 'PushButton', 'String',...
    'Stim OFF', 'Callback', {@turn_stim_off, inst_2},...
    'Units', 'normalized', 'Position', [0 .58 1 .2],...
    'BackgroundColor', 'green');

group_text_2 = uicontrol(panel_2, 'Style','text', 'String', ...
    'Switch to: ', 'Units', 'normalized','Position', [0 .44 1 .12], ...
    'FontWeight', 'bold');

groups_popup_2 = uicontrol(panel_2, 'Style', 'popup',...
    'String', {'Group A', 'Group B', 'Group C', 'Group D'},...
    'Callback', {@switch_groups, inst_2}, 'Units', 'normalized',...
    'Position', [0 .2 1 .08]);